# Generated by Django 3.2.5 on 2021-07-19 03:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='python',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('question', models.CharField(max_length=500)),
                ('options1', models.CharField(max_length=100)),
                ('options2', models.CharField(max_length=100)),
                ('options3', models.CharField(max_length=100)),
                ('options4', models.CharField(max_length=100)),
                ('ans', models.CharField(max_length=50)),
            ],
        ),
    ]
