# Generated by Django 3.2.5 on 2021-07-20 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=60)),
                ('email', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=50)),
                ('otp', models.IntegerField(max_length=10)),
                ('validation', models.CharField(max_length=4)),
            ],
        ),
    ]
