# Generated by Django 3.2.5 on 2021-07-21 02:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0003_auto_20210721_0129'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cplus',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('question', models.CharField(max_length=500)),
                ('options1', models.CharField(max_length=100)),
                ('options2', models.CharField(max_length=100)),
                ('options3', models.CharField(max_length=100)),
                ('options4', models.CharField(max_length=100)),
                ('ans', models.CharField(max_length=50)),
            ],
        ),
    ]
